version: "3.2"
services:
  master:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    networks:
      - db
    ports:
      - "3400:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
  listener:
    build: ./listener
    command: ./listen.sh
    networks:
      - db
networks:
  db:
volumes:
  mysqldata:
