version: "3.2"
services:
  master:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password --ssl --server-id=1
    volumes:
      - type: volume
        source: master
        target: /var/lib/mysql
    networks:
      - db
    ports:
      - "3400:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
  slave:
    build: ./slave
    command: --default-authentication-plugin=mysql_native_password --ssl --server-id=2 --relay-log=slave-relay-bin
    volumes:
      - type: volume
        source: slave
        target: /var/lib/mysql
    networks:
      - db
    ports:
      - "3401:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MAXWELL_USER=maxwell
      - MAXWELL_PASSWORD=test
      - MYSQL_MASTER_ROOT_PASSWORD=test
  maxwell:
    build: ./maxwell
    command: /run.sh
    networks:
      - db
    environment:
      - MAXWELL_USER=maxwell
      - MAXWELL_PASSWORD=test
networks:
  db:
volumes:
  master:
  slave:
