version: "3.2"
services:
  master:
    build: ./master
    command: --default-authentication-plugin=mysql_native_password --ssl
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    networks:
      - db
    ports:
      - "3400:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
  maxwell:
    build: ./maxwell
    command: /run.sh
    networks:
      - db
networks:
  db:
volumes:
  mysqldata:
